### ISSUE TITLE
[BUG] (wine) Unknown Error

### ISSUE THREAD

**Issue by GH0STP4WZ** [EnKdev/EnKdevs-Item-Trackers#1]
**Describe the bug**
Under wine, the program will consistently throw an unknown error when attempting to use cryptography.

**To Reproduce**
Save, or load a tracker state

**Expected behavior**
the tracker will not report an issue on save, but the log will record an unknown error (see attached log)
the tracker will show an error notice when attempting to load the bugged tracker state generated from saving under wine

**Additional context**
Tracker version: EnKdev.ItemTrackers.OoT V1.0.0
Included logfile: [07-03-2024.txt](https://github.com/EnKdev/EnKdevs-Item-Trackers/files/14530157/07-03-2024.txt)

**Comment by EnKdev** [comment]
Don't use the app on Linux and run it through Wine - as this is an application that's only expected to work fully on Windows.
The linux build of .NET might be lacking functionality which the app expects to exist, mostly related to the Cryptography features.
